apiVersion: sops.peakscale.ch/v1alpha1
kind: SopsProvider
metadata:
  name: sample-provider
spec:
  providers:
  - matchLabels:
      "sops-private-key": "true"
  sops:
  - matchLabels:
      "sops-secret": "true"
