---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopsproviders
  - sopssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopsproviders/finalizers
  - sopssecrets/finalizers
  verbs:
  - update
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopsproviders/status
  - sopssecrets/status
  verbs:
  - get
  - patch
  - update
