# permissions for end users to view sopssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sopssecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sops-operator
    app.kubernetes.io/part-of: sops-operator
    app.kubernetes.io/managed-by: kustomize
  name: sopssecret-viewer-role
rules:
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopssecrets/status
  verbs:
  - get
