# permissions for end users to edit sopsproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sopsprovider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sops-operator
    app.kubernetes.io/part-of: sops-operator
    app.kubernetes.io/managed-by: kustomize
  name: sopsprovider-editor-role
rules:
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sops.peakscale.ch
  resources:
  - sopsproviders/status
  verbs:
  - get
