apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-keys
resources:
  - ns.yaml
secretGenerator:
- name: private-key-1
  files:
  - sops.asc=private.key
  type: Opaque
  options:
    labels:
      "sops-private-key": "true"
